# Получение списка продуктов, отзывов, коллекций, заказов

###
GET http://localhost:8000/api/products/
###
GET http://localhost:8000/api/reviews/
###
GET http://localhost:8000/api/collections
###
GET http://localhost:8000/api/orders/
Authorization: Token 00b34e083af759bfad0f34932810d0401433d413


# ФИЛЬТРЫ И СОРТИРОВКА

# Фильтр заказов по товару
###
GET http://localhost:8000/api/orders/?products=10
Authorization: Token 54926bbd1248f690efdd8f7372ce7e1b64a8ea79
Content-Type: application/json

# Фильтр отзывов по пользователю
###
GET http://localhost:8000/api/reviews/?user_id=1
Content-Type: application/json

# Поиск товаров по названию
###
GET http://localhost:8000/api/products/?name=элек
Content-Type: application/json


# Сорировка заказов по статусу
###
GET http://localhost:8000/api/orders/?ordering=status
Authorization: Token 54926bbd1248f690efdd8f7372ce7e1b64a8ea79
Content-Type: application/json



# СОЗДАНИЕ И ИЗМЕНЕНИЕ

# Создание нового продукта
###
POST http://localhost:8000/api/products/
Content-Type: application/json
Authorization: Token 00b34e083af759bfad0f34932810d0401433d413

{
    "name" : "Пламягаситель neGORI-popa3001",
    "description" : "Отличное средство для тех, у кого не получаеся освоить Django",
    "price": 40000
}

# Создание новой коллекции
###
POST http://localhost:8000/api/collections/
Content-Type: application/json
Authorization: Token 54926bbd1248f690efdd8f7372ce7e1b64a8ea79

{
    "text" : "Тест",
    "heading" : "Тестовое описание",
    "products": [1,10]
}


# Создание нового заказа
###
POST http://localhost:8000/api/orders/
Content-Type: application/json
Authorization: Token 54926bbd1248f690efdd8f7372ce7e1b64a8ea79

{
    "order_products":
    [
        {
            "product" : 14,
            "quantity" : 1
        }
    ]
}

# Изменение состава заказа
###
PATCH http://localhost:8000/api/orders/212/
Content-Type: application/json
Authorization: Token 00b34e083af759bfad0f34932810d0401433d413

{
  "order_products": [
      {
      "quantity": 10,
      "product": 11
      },
      {
        "quantity" : 2,
        "product" : 14
      }
  ]  
}

# Попытка поменять статус заказа
###
PATCH http://localhost:8000/api/orders/209/
Content-Type: application/json
Authorization: Token 00b34e083af759bfad0f34932810d0401433d413

{
    "status" : "IN PROGRESS"
}

# Добавление отзыва на товар (при повторном добавлении выдает ошибку)
### 
POST http://localhost:8000/api/reviews/
Content-Type: application/json
Authorization: Token 54926bbd1248f690efdd8f7372ce7e1b64a8ea79

{
    "product_id": 17,
    "text": "Спасибо тебе, Наташа, за классный товар. Умнее я не стал, но припекать перестало.",
    "stars": 5
}

# Попытка поменять чужой отзыв
### 
PATCH  http://localhost:8000/api/reviews/5/
Content-Type: application/json
Authorization: Token 00b34e083af759bfad0f34932810d0401433d413

{
    "product_id": 17,
    "text": "Спасибо тебе, Наташа, за классный товар. Умнее я не стал, но припекать перестало.",
    "stars": 5
}


# Попытка поменять свой отзыв
### 
POST http://localhost:8000/api/reviews/
Content-Type: application/json
Authorization: Token 00b34e083af759bfad0f34932810d0401433d413

{
    "product_id": 16,
    "text": "Спасибо тебе, Наташа, за классный товар. Умнее я не стал, но припекать перестало.",
    "stars": 5
}
