# Generated by Django 3.1.2 on 2021-03-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210323_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='shop.ProductsOrders', to='shop.Product'),
        ),
    ]
