# Generated by Django 3.1.2 on 2021-03-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210327_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsorders',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='productsorders',
            old_name='product',
            new_name='product_id',
        ),
    ]
