# Generated by Django 3.1.2 on 2021-03-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210328_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsorders',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='productsorders',
            old_name='product_id',
            new_name='product',
        ),
    ]
