# Generated by Django 3.1.2 on 2021-04-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20210331_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='shop.ProductsOrders', to='shop.Product'),
        ),
    ]
